### ISSUE TITLE
Re-inject a packet from forward layer to local machine

### ISSUE THREAD

**Issue by rockvider** [TechnikEmpire/Divert.Net#1]
First I would like to thank you for this awesome .Net binding.

I would like to capture a tcp packet at the forwarding layer and then re-inject it with the local machine as the destination while changing also the destination port, So I've opened two windivert handles one for the network layer and one for the forwarding layer, the packets are captured on the forwarding layer but it seems they are not injected properly (I've a tcp listener on the new destination port and it is not receiving the packets nor wireshark is capturing it)

I've modified the sample coming with Divert.net by opening another windivert handle using the following code:

```
     networkDiversion = Diversion.Open("tcp", DivertLayer.Network, 0, 0);
```

And modified the open arguments for the sample to the following:

```
     diversion = Diversion.Open(filter, DivertLayer.NetworkForward, -1000, 0);
```

And on the main loop which handles the forwarding packet I've added this code:

```
                    if (tcpHeader.DestinationPort == 80)
                    {
                        ipHeader.DestinationAddress = IPAddress.Parse("192.168.1.5"); //Ip of the local machine
                        tcpHeader.DestinationPort = 87;
                        address.Direction = DivertDirection.Inbound;
                        networkDiversion.CalculateChecksums(buffer, receiveLength, 0);
                        networkDiversion.Send(buffer, receiveLength, address, ref sendLength);
                        continue;
                    }
```

So is there something wrong i'm doing?

Btw DestinationPort property of the tcp header has an issue and always sets the port to zero, it is missing a casting to short:

```
        void TCPHeader::DestinationPort::set(uint16_t value)
        {
            if (m_tcpHeader != nullptr)
            {
                m_tcpHeader->DstPort = System::Net::IPAddress::HostToNetworkOrder((short)value);
            }
        }
```

Thanks

**Comment by TechnikEmpire** [comment]
Hey @rockvider , so where you're putting `IPAddress.Parse("192.168.1.5")` and saying `local machine` I'm assuming you're just trying to divert the packets on your own machine back to your own machine yes? For something like an intercepting proxy? 

Also, thanks for the bug report! Let me know when you find something else because there probably will be, I brought this code together really fast.

**Comment by rockvider** [comment]
So my setup involves 2 machines:
192.168.1.100: Which is doing a request to 7.7.7.7:80 (for example)
192.168.1.5: the machine which has my application running with Divert.net

On 192.168.1.5 I receive a packet on the forwarding layer going from 192.168.1.100:5000 --> 7.7.7.7:80

I want to drop this packet, modify then inject it to the local machine tcp stack using a network layer Diversion to be 192.168.1.100:5000 --> 192.168.1.5:87

So yes what i'm trying to do is something like an intercepting proxy, I've a tcp socket listening to 192.168.1.5:87 which will receive the request from 192.168.1.100 then send it to another remote machine which will then send it finally to 7.7.7.7:80 and vice versa.

Thanks for your help and sorry for the long post.

Sure I'll report any issue I come around.

**Comment by TechnikEmpire** [comment]
@rockvider So the machine `192.168.1.5` wants to intercept, direct the packet inbound on to itself, where I assume you have a socket or something listening on 87 that will read the incoming request, then write a response back out? Sorry I just want to make sure I fully grasp the issue before I start throwing suggestions around. 

I'm still having my morning coffee, I'll get back to you in a few.

**Comment by rockvider** [comment]
Exactly

**Comment by TechnikEmpire** [comment]
It'd be helpful if I could see the full source code, I can only guess really. I'm leaning towards it being that your own Diversion filters are catching the packets after you send them to your local machine, port 87. Notice how your network layer filter is simply "tcp". 

This is going to eat up both inbound and outbound TCP connections of any kind on your local machine. You need to heavily use the `Address.Direction` parameters plus ip/port params to decide which packets to modify and not modify properly. 

Also remember that you need to have code which is providing a reverse route back to the original host. Somewhere in your `networkDiversion` loop you're going to need to check for conditions where you need to pop that packet out and modify the IP, ports and direction back to the correct values that the original host machine is expecting for a response.

On another note, you're probably going to need to get the Process ID of the machine running the diversion, and use the extra API I provided for getting the process ID attached to the packet. The reason for this is that you'll want to ensure you're not sweeping up the proxy's outbound connection to `realdestination:80`. Without it, how can your diversion filters differentiate between outbound packets you really want to go outbound, and outbound packets you want to force back inbound? So yeah, could be a couple of things.

**Comment by TechnikEmpire** [comment]
Ugh, disregard the last bit about process ID. My brain is stuck thinking that client and proxy are the same machine. See, coffee isn't kicking in yet. ;)

**Comment by rockvider** [comment]
This is the netdump sample modified quickly with everything hardcoded, also I've a socket listenting on 87 and I never get any tcp connections, though I get packets coming from local machine (192.168.1.5:87) going to 192.168.1.100 where I've this comment: " //I DO GET PACKETS HERE??":

```
    Diversion diversion;
            Diversion networkDiversion;
            string filter = "true";

            try
            {   
                diversion = Diversion.Open(filter, DivertLayer.NetworkForward, -1000, 0);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return;
            }

            try
            {
                networkDiversion = Diversion.Open("tcp", DivertLayer.Network, 0, 0);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return;
            }

            Thread thread = new Thread(() =>
            {
                Address networking_address = new Address();
                byte[] networking_buffer = new byte[65535];

                uint networking_receiveLength = 0;
                uint networking_sendLength = 0;
                IPHeader networking_ipHeader = new IPHeader();
                TCPHeader networking_tcpHeader = new TCPHeader();
                while (running)
                {
                    if (!networkDiversion.Receive(networking_buffer, networking_address, ref networking_receiveLength))
                    {
                        Console.WriteLine("Failed to receive packet with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                        continue;
                    }

                    networkDiversion.ParsePacket(networking_buffer, networking_receiveLength, networking_ipHeader, null, null, null, networking_tcpHeader, null);

                    if (networking_ipHeader.Valid && networking_tcpHeader.Valid)
                    {       
                        Console.WriteLine( "{0} - (Network layer) IPv4 TCP packet captured destined for {1}:{2} from {3}:{4}.", 
                        networking_address.Direction == DivertDirection.Inbound ? "Inbound" : "Outbound", 
                        networking_ipHeader.DestinationAddress.ToString(), networking_tcpHeader.DestinationPort.ToString(), 
                        networking_ipHeader.SourceAddress.ToString(), networking_tcpHeader.SourcePort.ToString()
                        );

                        if (networking_tcpHeader.SourcePort == 87 && networking_ipHeader.DestinationAddress.ToString() == "192.168.1.100")
                        {
                            //I DO GET PACKETS HERE??
                            networking_ipHeader.SourceAddress = IPAddress.Parse("184.168.47.225");
                            networking_tcpHeader.SourcePort = 80;
                            networkDiversion.CalculateChecksums(networking_buffer, networking_receiveLength, 0);
                        }

                        if (networking_ipHeader.SourceAddress.ToString() == "192.168.1.100" && networking_tcpHeader.DestinationPort == 87)
                        {
                            Console.WriteLine("Intercepted packet");
                        }
                    }

                    networkDiversion.SendAsync(networking_buffer, networking_receiveLength, networking_address, ref networking_sendLength);
                }
            });

            thread.Start();

            if(!diversion.Handle.Valid)
            {
                Console.WriteLine("Failed to open divert handle with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                return;
            }

            IPHeader ipHeader = new IPHeader();
            IPv6Header ipv6Header = new IPv6Header();
            ICMPHeader icmpHeader = new ICMPHeader();
            ICMPv6Header icmpv6Header = new ICMPv6Header();
            TCPHeader tcpHeader = new TCPHeader();
            UDPHeader udpHeader = new UDPHeader();

            Address address = new Address();

            byte[] buffer = new byte[65535];

            uint receiveLength = 0;
            uint sendLength = 0;

            string processName = "";

            uint pid = 0;

            while (running)
            {
                pid = 0;

                receiveLength = 0;
                sendLength = 0;

                if (!diversion.Receive(buffer, address, ref receiveLength))
                {
                    Console.WriteLine("Failed to receive packet with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                    continue;
                }

                diversion.ParsePacket(buffer, receiveLength, ipHeader, ipv6Header, icmpHeader, icmpv6Header, tcpHeader, udpHeader);

                if (ipHeader.Valid && tcpHeader.Valid)
                {                    
                    Console.WriteLine(
                        "{0} IPv4 TCP packet captured destined for {1}:{2} from {3}:{4} {5}.", 
                        address.Direction == DivertDirection.Inbound ? "Inbound" : "Outbound", 
                        ipHeader.DestinationAddress.ToString(), tcpHeader.DestinationPort.ToString(), 
                        ipHeader.SourceAddress.ToString(), tcpHeader.SourcePort.ToString(),
                        address.Direction == DivertDirection.Inbound ? string.Format("to process {0}", processName) : string.Format("from process {0}", processName)
                        );

                    if (tcpHeader.DestinationPort == 80)
                    {
                        ipHeader.DestinationAddress = IPAddress.Parse("192.168.1.5");
                        tcpHeader.DestinationPort = 87;
                        address.Direction = DivertDirection.Inbound;
                        networkDiversion.CalculateChecksums(buffer, receiveLength, 0);
                        networkDiversion.Send(buffer, receiveLength, address, ref sendLength);
                        continue;
                    }
                }

                diversion.SendAsync(buffer, receiveLength, address, ref sendLength);
            }

            networkDiversion.Close();
            diversion.Close();
```

**Comment by TechnikEmpire** [comment]
There's a few things but honestly I'd have to rewrite a lot of your code to fix it all. You can solve the issue by drawing out the network flow. In your loop for capturing the local network traffic and diverting it to your socket, you don't change the direction of the packet to Inbound. The direction is most likely outbound, but for it to go to your socket instead, it needs to be injected as an inbound packet.

It seems you only have a condition where the packets are outbound from your socket, which seems to be correct. If its outbound from your socket, leave the direction as outbound, but modify the source and destination IP addresses and ports to match what the client is expecting. Remember you need to have two routing mechanisms, one to route outbound traffic back inbound to your intercepting proxy, one to provide the correct return route. Fixing the missing direction code and see if that help. Beyond that, stackoverflow might be a good place to post. 

I'm going to leave this issue open because the fix for the bug you reference hasn't been committed yet. I'll close it once I commit. Thanks again for the report. :)

**Comment by TechnikEmpire** [comment]
Discovered lots of issues with value conversion. Hard to diagnose this issue due to not having everything needed to replicate. Suggest re-trying from latest version and if the question isn't a bug, but rather a question of "how to", to post one StackOverflow. If there is a bug, please open a new issue with specifics. Thanks!
