### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mhenkel1** [TechnikEmpire/Divert.Net#11]
Fehler  C3861   "WinDivertHelperCheckFilter": Bezeichner wurde nicht gefunden.  Divert.Net  F:\Divert.Net-master\Divert.Net-master\src\Diversion.cpp    142 
Fehler  C3861   "WinDivertHelperEvalFilter": Bezeichner wurde nicht gefunden.   Divert.Net  F:\Divert.Net-master\Divert.Net-master\src\Diversion.cpp    178 

I am not able to run the example at all, because of the missing Divert.Net DLL.
But I am also not able to compile the Divert.Net Dll from the project.

**Comment by TechnikEmpire** [comment]
@mhenkel1 You need to download WinDivert and stage it correctly to compile this project. See the wiki:

https://github.com/TechnikEmpire/Divert.Net/wiki

Also, notice that you can skip compiling this project and give my new PInvoke version a shot. Just make sure obviously that you copy the WinDivert binaries to your program output directory.

https://github.com/TechnikEmpire/DivertPInvoke
