### ISSUE TITLE
I can't run example

### ISSUE THREAD

**Issue by VerifyBlind** [TechnikEmpire/Divert.Net#13]
Hi, 
  I download as zip and open NetDump.sln on VS2012. I got a warning : "The referenced component 'Divert.Net' could not be found." and of course related "... does not exists in the current context."

Is Divert.Net dll? How can i add or how can fix this problem?

**Comment by TechnikEmpire** [comment]
@ercumenteskar divert .net is quite obviously a dll that you compile to link against the Windivert library. Please don't open and close issues to get my attention. If it was an accident, ignore that last comment.

There are instructions right on the project page for building and such. However, I would recommend simply using the PInvoke version. There is a separate repository of mine for this single class.
