### ISSUE TITLE
TcpHeader.HeaderLength incorrect

### ISSUE THREAD

**Issue by GF-Huang** [TechnikEmpire/Divert.Net#18]
![image](https://user-images.githubusercontent.com/4510984/34524808-ced2b466-f0d7-11e7-9aaf-08cfc98374ef.png)

**Comment by TechnikEmpire** [comment]
Hmmm yeah that doesn't seem right. I'll have to look at the source code.

If you don't care about enabling unsafe code, just use my divert pinvoke library (look at my repositories to find it). It's a single .cs file derived directly from the windivert header, with a couple of convenience properties that do automatic network to host and host to network conversion on things like it addresses and port numbers.

**Comment by GF-Huang** [comment]
ok, thank you. 
I have seen your codes in DivertPInvoke.cs, i think make a Endianness Checking before SwapOrder is more safer, although our codes most time run in little endianness platform.
The ```IPAddress.HostToNetworkOrder``` and ```IPAddress.NetworkToHostOrder``` is useful to do this.

**Comment by TechnikEmpire** [comment]
I don't need to check endianness because windows desktop is always little endian so swap will always be required and always be accurate.

I'm talking about the pinvoke version obviously. There could be a bug with swapping in here with what you've reported.

**Comment by GF-Huang** [comment]
:) understand, thank you.

**Comment by GF-Huang** [comment]
I found another question that is the layout of struct ```WINDIVERT_TCPHDR```  different to "TCP segment structure" 

WINDIVERT_TCPHDR:
![image](https://user-images.githubusercontent.com/4510984/34551871-86cd238c-f158-11e7-9ba1-ce279ba22409.png)

TCP segment structure defines in Wiki (https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure):
![image](https://user-images.githubusercontent.com/4510984/34551906-d51252b0-f158-11e7-9fd9-79a5e384afba.png)

RFC793 - Transmission Control Protocol (https://tools.ietf.org/html/rfc793#page-15):
![image](https://user-images.githubusercontent.com/4510984/34551940-33348e44-f159-11e7-8f5d-f329ccbeb445.png)

**Comment by TechnikEmpire** [comment]
If you look at the windivert helper methods, there are are functions available to read those fields properly. I know it appears to be out of order but all it is, is cramming labels on to 16 bits of continuous data.

If there is an issue with that layout and functions needed to properly read and write those fields, please open a bug ticket on WinDivert's repo. I'll see it.
