### ISSUE TITLE
Compiling for x86 causes unknown external symbol errors

### ISSUE THREAD

**Issue by mrparkerlol** [TechnikEmpire/Divert.Net#19]
When selecting "Debug x86" drop the drop-down, it kicks out errors:

![devenv_2018-02-20_23-36-18](https://user-images.githubusercontent.com/2037716/36468103-e495bbf6-1696-11e8-8c23-3f05a8038d81.png)

I have followed the Wiki closely and funnily enough the 64-bit build succeeds, but the 32bit fails with the external symbols.

**Comment by TechnikEmpire** [comment]
I'll look into this, but you should just look at https://github.com/TechnikEmpire/DivertPInvoke

This way you don't have to mess about with compiling and intermediary DLL.

You can see a more complex example of the pinvoke wrapper here:

https://github.com/TechnikEmpire/CitadelCore.Windows/tree/master/CitadelCore.Windows/CitadelCore.Windows/Diversion

**Comment by mrparkerlol** [comment]
I originally came across this project as a wrapper for c++, unknowingly it was a DLL for C# projects.

I also opened an issue at the main Divert repo as well detailing these issues (specifically with the "webfilter.c" demo):
https://github.com/basil00/Divert/issues/122

I noticed it was probably more than just your library and might be a separate issue.

Thank you for responding.
