### ISSUE TITLE
Use this as a TCP Proxy/Redirector

### ISSUE THREAD

**Issue by username-not-important** [TechnikEmpire/Divert.Net#22]
Can I use this package to create my TCP redirector (similar to a proxy and a load balancer) without worrying about SYN and ACK value calculations?

**Comment by TechnikEmpire** [comment]
First of all use the pinvoke wrapper linked in the readme, it's much simpler. Secondly, you can redirect, inject and modify packets howsoever you please. Have a look at CitadelCore.Windows or HttpFilteringEngine (both my repos) where I use this library to transparently redirect packets through a filtering proxy.
