### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by Van-hoa** [TechnikEmpire/Divert.Net#23]
Hi ! 

I want to know : Can we use Divert dot net with .net core ?
If we can, there is something special to do ? 

Thank's.

**Comment by TechnikEmpire** [comment]
Just use my other repository which is simply a single .CS source file. Not however that it is only compatible with WinDivert 1.3. WinDivert does not use semantic versioning, so 1.4 is not API compatible.

https://github.com/TechnikEmpire/DivertPInvoke

I use WinDivert in .net standard library myself here: 
https://github.com/TechnikEmpire/CitadelCore.Windows
