### ISSUE TITLE
package.nuspec does not include assemblies.

### ISSUE THREAD

**Issue by agklaver** [TechnikEmpire/Divert.Net#4]
`nuget pack` is not including any of the project assemblies.

@TechnikEmpire P.S. Hoping to see this make it's way to nuget.org

**Comment by TechnikEmpire** [comment]
@agklaver Yeah I never got around to this. I was hasty with comitting the nuget project here, as I basically just created it and then stopped. I would like to bring it to nuget, but I'm swamped with work and I've got a bunch of outstanding issues on other projects I have to deal with first. :worried:

**Comment by TechnikEmpire** [comment]
Closed because nuget is not a target.
