### ISSUE TITLE
Adding data to payload

### ISSUE THREAD

**Issue by oasrog** [TechnikEmpire/Divert.Net#6]
Hi,

Thank you very much for this great binding!

I succeeded in modifying the payload content without touching the length of the incoming buffer, but cannot "add" extra content to it.

Is it possible to do this? This is my actual code based on netdump example

``` C#
class Program
    {
        static void Main(string[] args)
        {
            Diversion diversion = Diversion.Open("true", DivertLayer.Network, 100, 0);

            IPHeader ipHeader = new IPHeader();
            IPv6Header ipv6Header = new IPv6Header();
            ICMPHeader icmpHeader = new ICMPHeader();
            ICMPv6Header icmpv6Header = new ICMPv6Header();
            TCPHeader tcpHeader = new TCPHeader();
            UDPHeader udpHeader = new UDPHeader();

            Address address = new Address();

            byte[] buffer = new byte[65535];
            byte[] newbuffer = new byte[1];

            uint receiveLength = 0;
            uint sendLength = 0;

            string processName;
            bool added = false;

            uint pid = 0;

            Console.WriteLine("Starting...");

            while (true)
            {
                added = false;
                pid = 0;

                receiveLength = 0;
                sendLength = 0;

                if (!diversion.Receive(buffer, address, ref receiveLength))
                {
                    Console.WriteLine("Failed to receive packet with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                    continue;
                }

                diversion.ParsePacket(buffer, receiveLength, ipHeader, ipv6Header, icmpHeader, icmpv6Header, tcpHeader, udpHeader);

                if (ipHeader.Valid && tcpHeader.Valid)
                {
                    Diversion.GetPacketProcess(address, tcpHeader, ipHeader, ref pid, out processName);

                    string processexecutable = processName.Substring(processName.LastIndexOf('\\')+1);

                    if (processexecutable == "client.exe" && address.Direction == DivertDirection.Inbound)
                    {                        
                        string recibido = Encoding.UTF8.GetString(buffer);

                        Console.WriteLine("Adding");
                        added = true;

                        //Adding new data
                        buffer[receiveLength + 1] = 72;
                        buffer[receiveLength + 2] = 79;
                        buffer[receiveLength + 3] = 76;
                        buffer[receiveLength + 4] = 65;

                        //Creating new buffer
                        newbuffer = new byte[receiveLength + 4];

                        Array.Copy(buffer, newbuffer, receiveLength + 4);

                        //Modifying existing data (OK)
                        //buffer[296] = 72;
                    }                    
                }

                if (!added)
                {
                    diversion.CalculateChecksums(buffer, receiveLength, 0);
                    diversion.SendAsync(buffer, receiveLength, address, ref sendLength);
                }
                else
                {
                    diversion.CalculateChecksums(newbuffer, Convert.ToUInt32(newbuffer.Length), 0);

                    if (!diversion.SendAsync(newbuffer, Convert.ToUInt32(newbuffer.Length), address, ref sendLength))
                        Console.WriteLine("FAILED!");
                }                                  
            }

            diversion.Close();
        }
    }
```

I would very much appreciate if you can point me in the right direction regarding this issue.

**Comment by TechnikEmpire** [comment]
@oasrog Are you getting a particular error or something?

**Comment by oasrog** [comment]
Hi,

Thank you for your answer.

I only get a false when calling sendasync method and the packet never
reaches the application

By the way, both client.exe and the divert.net application are running on
the same computer.

I'm trying to intercept and modify the incoming payload for that specific
app adding a few characters.

Thanks for your help

**Comment by TechnikEmpire** [comment]
@oasrog Try using just the regular send function and if you get a failure, call `Marshal.GetLastWin32Error()` and provide the returned error code here please.

**Comment by oasrog** [comment]
Hi,

I've added the code suggested and got back 87 as GetLastWin32Error()

if (!diversion.Send(newbuffer, Convert.ToUInt32(newbuffer.Length), address,
ref sendLength))
                        Console.WriteLine(Marshal.GetLastWin32Error());

Sergio

**Comment by oasrog** [comment]
As stated in MSFT web, this is the meaning of this error

ERROR_INVALID_PARAMETER
87 (0x57)
The parameter is incorrect.

I guess the byte[] payload I'm passing as parameter is wrong

Sergio

On Sun, Jun 12, 2016 at 4:54 PM, Sergio Fernandez <fernandezsergio@gmail.com

**Comment by TechnikEmpire** [comment]
@oasrog Very interesting, perhaps you've found a legit bug! (as if that's a shock, haha). Let me look at this a little closer.

**Comment by oasrog** [comment]
haha, well, let me know if I can help you!

Sergio

**Comment by PhyxionNL** [comment]
Code looks fine at least.

**Comment by TechnikEmpire** [comment]
I've never actually modified the packets, just re-routed them. However, I think that part of the issue might be that you need to get a copy of the actual packet payload, and then re-construct the packet after modifying the payload. One of the overloads provides this functionality in WinDivert and IIRC, that overload should be here as well. The reason for this is that the packet layout cannot be guaranteed to be in such a way that the trailing bits are actually payload bits, or the payload bits for the specific portion of the packet that you're editing. 

I suspect that if you dump the packet and inspect in manually you'll be able to confirm this (that the trailing bits you're appending to go beyond the payload buffer storage portion of the packet).

**Comment by TechnikEmpire** [comment]
@oasrog any update on this after my comments? It's impossible for me to accurately test because I don't have your entire test data. Let me know if my last comment and debugging nfo I suggested sheds any light. Thanks.

**Comment by oasrog** [comment]
Jesse,

I haven´t been able to do further testing, but I will get back to you as
soon as I can.

Thank you for your help!

Sergio

**Comment by TechnikEmpire** [comment]
@oasrog How'd this turn out?

**Comment by oasrog** [comment]
Jesse,

I've abandoned the project so far, my current job is getting 110℅ of my
time.

I hope someday I can get some spare time to continue with other personal
projects.

**Comment by TechnikEmpire** [comment]
@oasrog Alright I'm going to close this out.
