### ISSUE TITLE
Sequence numbers and ip header lengths incorrect

### ISSUE THREAD

**Issue by OSSIndex-Admin** [TechnikEmpire/Divert.Net#7]
Hi.

First off, thanks for the library!

It is quite possible that I have done something incorrect in my code, but I am not being returned correct sequence numbers or packet lengths. I have not fully verified other values at this point.

My program is a simple modification of the example program, which writes sequence numbers and lengths for packets arriving from a target host:port. While running the program I simultaneously ran WireShark for validation.

Upon running a simple request from the host I received the following dump. You will note that the packets (third column) are not in sequence.

```
Handle to WinDivert1.2 driver successfully opened in packet sniffing mode.
Reporting packets coming from a secure server (SSL)...
37 SEQ <2563662208>: 159.203.26.198:443->192.168.1.2 13312
40 SEQ <2580439424>: 159.203.26.198:443->192.168.1.2 5125
41 SEQ <2245222784>: 159.203.26.198:443->192.168.1.2 5125
42 SEQ <1910006144>: 159.203.26.198:443->192.168.1.2 21763
45 SEQ <2665177472>: 159.203.26.198:443->192.168.1.2 25344
47 SEQ <3655033216>: 159.203.26.198:443->192.168.1.2 5125
48 SEQ <3319816576>: 159.203.26.198:443->192.168.1.2 5125
49 SEQ <2984599936>: 159.203.26.198:443->192.168.1.2 5125
51 SEQ <2649383296>: 159.203.26.198:443->192.168.1.2 5125
52 SEQ <2314166656>: 159.203.26.198:443->192.168.1.2 5125
53 SEQ <1978950016>: 159.203.26.198:443->192.168.1.2 5125
54 SEQ <1643733376>: 159.203.26.198:443->192.168.1.2 42243
55 SEQ <3741081984>: 159.203.26.198:443->192.168.1.2 5125
57 SEQ <3389088384>: 159.203.26.198:443->192.168.1.2 5125
58 SEQ <3053871744>: 159.203.26.198:443->192.168.1.2 5125
60 SEQ <2718655104>: 159.203.26.198:443->192.168.1.2 5125
61 SEQ <2383438464>: 159.203.26.198:443->192.168.1.2 45570
77 SEQ <420700800>: 159.203.26.198:443->192.168.1.2 10240
78 SEQ <420700800>: 159.203.26.198:443->192.168.1.2 10240
```

Here is the screenshot from WireShark.

![wireshak](https://cloud.githubusercontent.com/assets/13612752/16364813/c9b5a50e-3bbd-11e6-956b-c4722b30cff2.png)

You can see that the packet numbers (first column in each case) follow the same pattern, though the numbers are mildly different. You will also see that both tools report the same number of packets.

The highlighted blue line (Transmission Control Protocol) shows the initial packet sequence number is 2153893528, which is completely different from that reported by the sample program. The packet lengths are similarly completely different (column 6 in WireShark, final column in sample program).

Any thoughts?

Thanks for the help.

The sample program source is here:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Divert.Net;

namespace NetDump
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WindowWidth = Console.LargestWindowWidth;
            bool running = true;

            Console.CancelKeyPress += delegate {running = false;};

            Diversion diversion;
            string filter = "true";

            try { diversion = Diversion.Open(filter, DivertLayer.Network, 100, FilterFlags.Sniff); }
            catch(Exception e) { Console.WriteLine(e.Message); return; }

            if(!diversion.Handle.Valid)
            {
                Console.WriteLine("Failed to open divert handle with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                return;
            }
            else
            {
                Console.WriteLine("Handle to WinDivert1.2 driver successfully opened in packet sniffing mode.");
                Console.WriteLine("Reporting packets coming from a secure server (SSL)...");
            }

            IPHeader ipHeader = new IPHeader();
            IPv6Header ipv6Header = new IPv6Header();
            ICMPHeader icmpHeader = new ICMPHeader();
            ICMPv6Header icmpv6Header = new ICMPv6Header();
            TCPHeader tcpHeader = new TCPHeader();
            UDPHeader udpHeader = new UDPHeader();

            Address address = new Address();
            byte[] buffer = new byte[65535];

            int count = 0;
            while (running)
            {
                count++;
                uint receiveLength = 0;

                if (!diversion.Receive(buffer, address, ref receiveLength))
                {
                    Console.WriteLine("Failed to receive packet with error {0}", System.Runtime.InteropServices.Marshal.GetLastWin32Error());
                    continue;
                }

                diversion.ParsePacket(buffer, receiveLength, ipHeader, ipv6Header, icmpHeader, icmpv6Header, tcpHeader, udpHeader);

                if (ipHeader.Valid && tcpHeader.Valid)
                {
                    string src = ipHeader.SourceAddress.ToString();
                    string dst = ipHeader.DestinationAddress.ToString();
                    long length = ipHeader.Length;
                    uint seq = tcpHeader.SequenceNumber;
                    ushort port = tcpHeader.SourcePort;

                    if (src == "159.203.26.198" && port == 443)
                    {
                        Console.WriteLine("{0} SEQ <{1}>: {2}:{3}->{4} {5}", count, seq, src, port, dst, length);
                        Console.WriteLine("");
                    }
                }
            }

            diversion.Close();
        }
    }
}

```

**Comment by TechnikEmpire** [comment]
@OSSIndex Right off the bat, the length could possibly be explained this way. The length parameter in WinDivert is meant to represent the entire length of the whole packet raw data. In Wireshark, this is not the case. Searches tell me that the length/data omits certain portions of the packet. I'll look into the other and get back to you.

**Comment by TechnikEmpire** [comment]
@OSSIndex For the "no", this can be explained away by simple differences between how your app and wireshark are choosing to increment counts. Last, the seq/ack I'll look into, this I think is the only thing that needs to be investigated here. Thanks for the report.

**Comment by OSSIndex-Admin** [comment]
Thanks. I wasn't worried about the "no" value, I just highlighted its use to show that it appears WireShark and Divert.Net were seeing the same packets in what would appear to be the same order (since the gaps between numbers are pretty darn uniform.)

I am uncertain about the length issue still. In my actual application I know the size of my data ranges between 1000-3000 bytes, but Divert appears to be reporting that the packets are carrying in excess of 200000 bytes (!). Packet overhead (and SSL overhead) should not be that excessive. I have similar programs in Linux that report closer to what I expect.

I have a couple of theories on what might be happening and will do some testing of my own and let you know if I find anything of use.

Thanks for the quick response!

**Comment by TechnikEmpire** [comment]
@OSSIndex It's very possible that I screwed up my unmanaged->managed conversions. I'm going to review them. You can try suppying the payload array out parameter and checking its length in the right receive overload. That will copy the actual payload to a new byte array, instead of the entire raw packet structure that WinDivert is giving you. Note that this project was thrown together I think over the course of a couple of days. lol, so mistakes are definitely on the table.

**Comment by OSSIndex-Admin** [comment]
Ah, I think I might have found it. The sequence and length (and probably other int values of various sorts) are stored in the packets in BigEndian, and it looks like WinDivert does not convert into LittleEndian.

I added some small conversion routines and updated the sample program like this:

```
...
                    UInt16 lengthBE = ipHeader.Length;
                    UInt16 lengthLE = ReverseBytes(lengthBE);
                    UInt32 seqBE = tcpHeader.SequenceNumber;
                    UInt32 seqLE = ReverseBytes(seqBE);
                    ushort port = tcpHeader.SourcePort;

                    if (src == "159.203.26.198" && port == 443)
                    {
                        Console.WriteLine("{0} BigEndian    <{1}>: {2}:{3}->{4} {5}", count, seqBE, src, port, dst, lengthBE);
                        Console.WriteLine("{0} LittleEndian <{1}>: {2}:{3}->{4} {5}", count, seqLE, src, port, dst, lengthLE);
                        Console.WriteLine("");
                    }
...
```

Which gives the following output (the second line in each cluster is the new "LittleEndian" version.) This data looks like it might be correct -- it is certainly closer.

```
Handle to WinDivert1.2 driver successfully opened in packet sniffing mode.
Reporting packets coming from a secure server (SSL)...
37 BigEndian    <4178333698>: 159.203.26.198:443->192.168.1.2 13312
37 LittleEndian <38800633>: 159.203.26.198:443->192.168.1.2 52

40 BigEndian    <4195110914>: 159.203.26.198:443->192.168.1.2 5125
40 LittleEndian <38800634>: 159.203.26.198:443->192.168.1.2 1300

41 BigEndian    <3859894274>: 159.203.26.198:443->192.168.1.2 5125
41 LittleEndian <38801894>: 159.203.26.198:443->192.168.1.2 1300

43 BigEndian    <3524677634>: 159.203.26.198:443->192.168.1.2 21763
43 LittleEndian <38803154>: 159.203.26.198:443->192.168.1.2 853

46 BigEndian    <4279848962>: 159.203.26.198:443->192.168.1.2 25344
46 LittleEndian <38803967>: 159.203.26.198:443->192.168.1.2 99

48 BigEndian    <974802946>: 159.203.26.198:443->192.168.1.2 5125
48 LittleEndian <38804026>: 159.203.26.198:443->192.168.1.2 1300

49 BigEndian    <639586306>: 159.203.26.198:443->192.168.1.2 5125
49 LittleEndian <38805286>: 159.203.26.198:443->192.168.1.2 1300

50 BigEndian    <304369666>: 159.203.26.198:443->192.168.1.2 5125
50 LittleEndian <38806546>: 159.203.26.198:443->192.168.1.2 1300

52 BigEndian    <4264054786>: 159.203.26.198:443->192.168.1.2 5125
52 LittleEndian <38807806>: 159.203.26.198:443->192.168.1.2 1300

53 BigEndian    <3928838146>: 159.203.26.198:443->192.168.1.2 5125
53 LittleEndian <38809066>: 159.203.26.198:443->192.168.1.2 1300

54 BigEndian    <3593621506>: 159.203.26.198:443->192.168.1.2 5125
54 LittleEndian <38810326>: 159.203.26.198:443->192.168.1.2 1300

56 BigEndian    <3258404866>: 159.203.26.198:443->192.168.1.2 5125
56 LittleEndian <38811586>: 159.203.26.198:443->192.168.1.2 1300

57 BigEndian    <2923188226>: 159.203.26.198:443->192.168.1.2 5125
57 LittleEndian <38812846>: 159.203.26.198:443->192.168.1.2 1300

58 BigEndian    <2587971586>: 159.203.26.198:443->192.168.1.2 5125
58 LittleEndian <38814106>: 159.203.26.198:443->192.168.1.2 1300

59 BigEndian    <2252754946>: 159.203.26.198:443->192.168.1.2 5125
59 LittleEndian <38815366>: 159.203.26.198:443->192.168.1.2 1300

61 BigEndian    <1917538306>: 159.203.26.198:443->192.168.1.2 5125
61 LittleEndian <38816626>: 159.203.26.198:443->192.168.1.2 1300

62 BigEndian    <1582321666>: 159.203.26.198:443->192.168.1.2 3585
62 LittleEndian <38817886>: 159.203.26.198:443->192.168.1.2 270

66 BigEndian    <1162956802>: 159.203.26.198:443->192.168.1.2 10240
66 LittleEndian <38818117>: 159.203.26.198:443->192.168.1.2 40

67 BigEndian    <1162956802>: 159.203.26.198:443->192.168.1.2 10240
67 LittleEndian <38818117>: 159.203.26.198:443->192.168.1.2 40
```

Here are the conversion routines I found [here](http://www.csharp-examples.net/reverse-bytes/)

```
        // reverse byte order (16-bit)
        public static UInt16 ReverseBytes(UInt16 value)
        {
            return (UInt16)((value & 0xFFU) << 8 | (value & 0xFF00U) >> 8);
        }

        // reverse byte order (32-bit)
        public static UInt32 ReverseBytes(UInt32 value)
        {
            return (value & 0x000000FFU) << 24 | (value & 0x0000FF00U) << 8 |
                   (value & 0x00FF0000U) >> 8 | (value & 0xFF000000U) >> 24;
        }

        // reverse byte order (64-bit)
        public static UInt64 ReverseBytes(UInt64 value)
        {
            return (value & 0x00000000000000FFUL) << 56 | (value & 0x000000000000FF00UL) << 40 |
                   (value & 0x0000000000FF0000UL) << 24 | (value & 0x00000000FF000000UL) << 8 |
                   (value & 0x000000FF00000000UL) >> 8 | (value & 0x0000FF0000000000UL) >> 24 |
                   (value & 0x00FF000000000000UL) >> 40 | (value & 0xFF00000000000000UL) >> 56;
        }
```

**Comment by TechnikEmpire** [comment]
@OSSIndex lol geeze, I only implemented conversion for port numbers and IP bytes. My bad. Good find! :+1:

**Comment by OSSIndex-Admin** [comment]
Heh. No problem.

Thanks again for the library and your fast response. It is enormously useful. I'm very glad we found it (it being Divert.Net).

**Comment by TechnikEmpire** [comment]
@OSSIndex See if that commit fixes your problems. All header fields are automatically converted to and from the proper ordering correctly. So, read and write fields expecting them to be in host order, the library will automatically handle the conversion. Feel free to re-open if I goofed up somewhere.

**Comment by OSSIndex-Admin** [comment]
I won't reopen yet, but I am not getting sequence numbers, lengths, or port numbers now :)

I am rather new to C# and Visual studio, so it is possible I am doing something wrong. I will do some extra debugging and reopen things once I have figured out what is going on.

Current output:

```
70 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
71 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
72 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
73 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
74 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
75 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
76 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
77 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
78 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
79 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
80 SEQ <0>: 192.168.1.2:0->157.56.106.189 0
81 SEQ <0>: 157.56.106.189:0->192.168.1.2 0
82 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
83 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
84 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
85 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
86 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
87 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
88 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
89 SEQ <0>: 192.168.1.1:0->192.168.1.2 0
90 SEQ <0>: 192.168.1.2:0->192.168.1.1 0
91 SEQ <0>: 192.168.1.2:0->224.0.0.251 0
92 SEQ <0>: 192.168.1.2:0->224.0.0.251 0
```

**Comment by TechnikEmpire** [comment]
@OSSIndex Nah it's possible that I just screwed it up. That's what I get for haphazardly committing stuff. I'll create an actual test program based on yours, review and fix it.

**Comment by TechnikEmpire** [comment]
@OSSIndex Yeah, I messed up a lot of stuff and there were some other things not being converted correctly either. You can test with latest commit. Basically my "fix" screwed things because I was trying to use CLR provided utilities to do to host-to-network and network-to-host. The available overloads rejected the data types in use in WinDivert (such as uint16/32/etc). This led to me thoughtlessly casting, either intentionally or not, to larger data types that fit those overloads input parameter types. Of course returning the resulting value after a reversal would mean all the bits you were interested in got shoved off a cliff, hence zero's. Should be sorted now, I think. ;)

**Comment by OSSIndex-Admin** [comment]
Beauty. Runs nicely with my test program. I will to build and test it with my main project later on Monday (all going well) and let you know if I see anything else, but everything else I was using was looking good.

First I need to figure out why my builds of Divert.Net don't work with my project -- but that is a problem with my inexperience with Visual Studio and nothing to do with you :)

**Comment by TechnikEmpire** [comment]
@OSSIndex Thanks for the feedback. Divert.NET is a mixed library of managed/unmanaged code that is compiled to specific platform targets (like x86, x64 etc). So when you go to include Divert.NET in, let's say, a C# WPF application, you need to change **that** project to be either x86, x64 etc. The default for such projects is "AnyCPU", which means the resulting binary is JIT'ed according to the host machine. If you don't explicitly disable AnyCPU when including Divert.NET, then you'll get target mismatches and it won't function correctly. That's the only reason I can think of off the top of my head.

There are solutions I could implement that sort of proxy from an AnyCPU target to plat-specific, but who has the time right?

**Comment by OSSIndex-Admin** [comment]
Ya, it appears the platform target was the issue. I must have somehow switched back to "AnyCPU" when installing the new version. Whoops. Meanwhile, everything is running nicely now.

I certainly won't be losing any sleep by having to specify the CPU :)

Thanks for the suggestion, BTW.
